-- FINANCIAL CORE V1 — write hardening
-- Apply after financial-core-v1.sql.

-- Affiliates/promoters may view attributed sales through RLS, but cannot create/edit sales or cash entries.
drop policy if exists sales_insert_scoped on public.sales;
create policy sales_insert_scoped on public.sales
for insert to authenticated
with check (
  public.is_financial_admin()
  or (
    public.has_role(array['supervisor','responsable','vendedor'])
    and (responsible_id = auth.uid() or created_by = auth.uid())
  )
);

drop policy if exists sales_update_scoped on public.sales;
create policy sales_update_scoped on public.sales
for update to authenticated
using (
  public.is_financial_admin()
  or (
    public.has_role(array['supervisor','responsable','vendedor'])
    and (responsible_id = auth.uid() or created_by = auth.uid())
  )
)
with check (
  public.is_financial_admin()
  or (
    public.has_role(array['supervisor','responsable','vendedor'])
    and (responsible_id = auth.uid() or created_by = auth.uid())
  )
);

drop policy if exists payments_insert_scoped on public.payments;
create policy payments_insert_scoped on public.payments
for insert to authenticated
with check (
  public.is_financial_admin()
  or (
    public.has_role(array['supervisor','responsable','vendedor'])
    and (responsible_id = auth.uid() or created_by = auth.uid())
  )
);

-- Payment correction/delete stays privileged-only.
drop policy if exists payments_update_privileged on public.payments;
create policy payments_update_privileged on public.payments
for update to authenticated
using (public.is_financial_admin())
with check (public.is_financial_admin());

drop policy if exists payments_delete_privileged on public.payments;
create policy payments_delete_privileged on public.payments
for delete to authenticated
using (public.is_financial_admin());

-- Direct commission creation is disabled for normal application users.
-- Commission rows are generated by security-definer payment triggers.
drop policy if exists commissions_insert_scoped on public.commissions;

-- Only Super Admin may delete a commission; Admin may approve/pay via UPDATE.
drop policy if exists commissions_delete_super_admin on public.commissions;
create policy commissions_delete_super_admin on public.commissions
for delete to authenticated
using (public.is_super_admin());
